[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
# dynamic_padding = true
blur = true
opacity = 0.75
padding = { x = 16, y = 16 }
option_as_alt = "Both"

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Beam", blinking = "Off" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    # macOS clipboard
    { key = "V", mods = "Super", action = "Paste" },
    { key = "C", mods = "Super", action = "Copy" },
    # Linux clipboard
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    # Shift+Enter for newline (useful in Claude Code)
    { key = "Return", mods = "Shift", chars = "\n" },
]
