[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = true
opacity = 5.0
padding = { x = 8, y = 8 }

[font]
size = 14.0

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Beam", blinking = "Off" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    # macOS clipboard
    { key = "V", mods = "Super", action = "Paste" },
    { key = "C", mods = "Super", action = "Copy" },
    # Linux clipboard
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
]
